### ISSUE TITLE
Additional support for date formats

### ISSUE THREAD

**Issue by MAB941009** [hauselin/obsidian-alfred#14]
Thank you Hauselin for the plugin. 

I'm speaking from my own usage here. I currently use the Moment.js date format ```YYYY-W-E ddd```, which at the moment doesn't seem supported. I've attached the difference between a daily note created in Obsidian, and one created via the plugin. It'd be super if these formats were supported too.

![dailynotesunsupportedformat@2x](https://user-images.githubusercontent.com/68162614/103155459-2bc71300-4798-11eb-85a4-be8e565a132d.png)

Other suggestions:

- [x] Option to open a default vault with keyword and/or keyboard shortcut
- [ ] Option to specify the inbox folder for new notes

**Comment by hauselin** [comment]
Try [this updated workflow](https://www.dropbox.com/s/gal6atk046h3vjt/Obsidian.alfredworkflow?dl=1) and let me know the date format works for you.

You can now open your last opened vault with a keyword (default: `obs`) or a hotkey (specify your own).

Finally, I don't think your last suggestion can be implemented easily/cleanly without bloating the workflow, so I won't try to implement it for now. I presume users will have different inbox folders for different vaults; if that's the case, creating a new note with `on` can become quite tedious, since users will have to first choose vault, then choose a folder in the vault, and finally indicate the note title. That's three steps to just create a blank/empty note... But let me know if you have thoughts/suggestions.

Also, you might notice a few extra keywords `oda`, `odt`, and `oa`. They're experimental features I'm testing, so you can ignore them for now. If you're an explorer, go ahead and try `oa`. It appends some text as a bullet point to the end of a selected note. But make sure your vaults are backed-up if you do choose to try these features.

**Comment by MAB941009** [comment]
@hauselin

I can confirm the latest version works with the date format. Along with quick access to daily notes, I have Obsidian opening rapidly via a keyboard shortcut too. Thanks.

AFAIK, all vaults will have their own inbox folders, because vaults only look down onto their sibling folders and thus cannot look horizontally to other vaults (unless vaults can be inside other vaults), but I'm unsure. In either case, I agree treading through multiple steps would defeat the goals of speed and efficiency. The best implementation I can think of is to include multiple daily note keywords and indicate the option to set up multiple vaults for the insertion of these notes. That'd improve the user experience, but would add clutter to the workflow interface. (Personally, I wouldn't mind the additional steps since Obsidian isn't my capturing app, so a delay would play into the role Obsidian serves for me.)

While I am adventurous, I've been hit with multiple arrows, so I'll hang back here! I like the idea nevertheless of appending to a note; I can certainly see multiple use cases.
