### ISSUE TITLE
Question os somekeyword does not search

### ISSUE THREAD

**Issue by tomer-ben-david** [hauselin/obsidian-alfred#16]
Hi, I have imported workflow to alfred connected to vault with oaddvault  but when i run in alfred "os somekeyword" although the keyword appears in my md and also as the md file name it does not find it.  Can you assist please?
thanks

**Comment by hauselin** [comment]
Can you try the solutions provided [here](https://github.com/hauselin/obsidian-alfred/issues/15#issuecomment-753414360)?

**Comment by tomer-ben-david** [comment]
Thanks! indeed seem to work - however looks like it's not limiting the search only to my vault - as I get results this is good enough for me thanks!

**Comment by hauselin** [comment]
Use `oss` if you want to limit search to only your vault (but note that `oss` requires you to first press enter before searching).

**Comment by tomer-ben-david** [comment]
perfect works. thanks!

**Comment by mk-uc** [comment]
Hopping in here. is there a way to reverse this so that `oss` allows you to simply enter a space and a search term after it, like `oss some file` and require `os` to use enter. I search my vault much more often than I want to search all markdown files, so changing this around would make it a little easier.
