### ISSUE TITLE
Improve settings for creating a new note

### ISSUE THREAD

**Issue by wenlzhang** [hauselin/obsidian-alfred#20]
Is it possible to support setting a default vault when creating a new note such that one does not need to select a vault each time when creating the note?

Also, is it possible to support adding template content when creating a new note? For instance, the following content may be added at the beginning of the newly created note:
```
---
title: {{title}}
created at: '{{date:YYYYMMDD}}{{time:HHmm}}'
---

# {{title}}

```

**Comment by hauselin** [comment]
> Is it possible to support setting a default vault when creating a new note such that one does not need to select a vault each time when creating the note?

Definitely possible. But before I try to make any changes, how about changing the create note script filter so that arguments are optional? That way, all your vaults will show up automatically/immediately when you type `on` and they will be sorted based on usage frequency, i.e., your most-used vault will be listed first. This way, you can very easily select your "default vault" (i.e., just press enter). Let me know whether this solution works for you.

![CleanShot 2021-02-14 at 09 03 35](https://user-images.githubusercontent.com/7620977/107880332-aad8ed80-6ea3-11eb-8c8d-8ed3a9cc6fcc.gif)


> Also, is it possible to support adding template content when creating a new note? For instance, the following content may be added at the beginning of the newly created note:

This one is difficult to implement because people will have many different templates and the user will have to indicate which template they want to use whenever they create a note. That's quite tedious (from my perspective) and Alfred also cannot easily populate the placeholders like `{{title}}` with actual content, which kind of makes inserting template via Alfred quite useless. Even Obsidian's [official action URI](https://publish.obsidian.md/help/Advanced+topics/Using+obsidian+URI#Action+new) doesn't support inserting templates when creating new notes yet.

**Comment by wenlzhang** [comment]
Thanks for the detailed explanations!

Regarding the first setting, I will use the suggested method.

Regarding the second setting, would it be possible that one set some parameters in the Alfred workflow for the mostly used template? In fact, I was using another Alfred workflow that was developed for The Archive for such a purpose. Specifically, the workflow creates a new note with the desired content and places the note in the desired folder set by the user. The workflow can be found as follows: 
https://forum.zettelkasten.de/discussion/675/alfred-workflow-for-creating-new-zettels-including-metadata

Part of the workflow can be seen from the following sreenshot:
![image](https://user-images.githubusercontent.com/44930227/107881691-ccf35f80-6ee5-11eb-98fe-819fda56855a.png)

Since that workflow was not developed for Obsidian, is it possible to somehow combine the "creating new note feature" of that workflow into obsidian-alfred?

**Comment by hauselin** [comment]
How are you expecting the feature to work? 

For example, this is your template. 

```
---
title: {{title}}
created at: '{{date:YYYYMMDD}}{{time:HHmm}}'
---

# {{title}}
```

When Alfred creates a new note and inserts the above template, do you expect the note to look like this (option 1):

```
---
title: {{title}}
created at: '{{date:YYYYMMDD}}{{time:HHmm}}'
---

# {{title}}
```

Or look something more like this (option 2)?

```
---
title: Hello world
created at: '202102141052'
---

# Hello world
```

Option 1 doesn't seem very useful so I'm guessing that's what not you want (since you'll have to open Obsidian to insert the template). If option 2 is what you want, it's quite difficult/tricky to cleanly implement. First (discussed above), people have many templates so I don't know what's the best way to keep track of all these templates (having 1 default template could work but I can imagine this solution might not work for many people who use many different templates equally frequently). Second, it's not easy to anticipate all the different possible placeholders people have in their templates. 

Given these considerations, I think the simplest way is to open Obsidian and insert the template in the app itself. For now,  I don't think it's worth the effort to implement this rather complicated feature in Alfred just to save a few keystrokes (open Obsidian, create note, insert template).

**Comment by wenlzhang** [comment]
I was expecting the option 2.

It makes sense that setting a default template may not be very useful for people having several frequently used templates.

Thanks for the replies, and I am closing this issue.
